### ISSUE TITLE
feat: Background Color

### ISSUE THREAD

**Issue by michaelbukachi** [TonnyL/WhatsNew#11]
It would be nice if we could be able to set a background color for the WhatsNew view. I'll probably open a pull request for this over the weekend. :)

**Comment by TonnyL** [comment]
Glad to see it. 😉

**Comment by michaelbukachi** [comment]
Hello. I noticed that you are using android-gradle-plugin version `3.5.0-alpha04` which is only available in canary  version of android studio. I've lowered it to `3.3.2`, I hope that's okay?

**Comment by TonnyL** [comment]
That's fine 😉.

**Comment by michaelbukachi** [comment]
Awesome. One more question. In a situation where both `backgroundColor` and `backgroundColorResource` are provided, which one should take priority?

**Comment by TonnyL** [comment]
In my opinion, `backgroundColorResource` should call `backgroundColor` internally.

**Comment by michaelbukachi** [comment]
With the current implementation, `backgroundColorResource` receives a resource integer instead of a color integer. That implementation will have to change for more flexibility.

**Comment by TonnyL** [comment]
You can modify it if it is reasonable.
