### ISSUE TITLE
ERROR: Failed to resolve: io.github.tonnyl:whatsnew:x.y.z .  -  Getting this error when adding this library.

### ISSUE THREAD

**Issue by karthickperumal** [TonnyL/WhatsNew#12]

**Comment by TonnyL** [comment]
`x.y.z` stands for the latest version number, by now, it's `0.1.2`.

**Comment by TonnyL** [comment]
@karthickperumal Any other question? If the answer is negative, I'll close this issue later. Feel free to reply or just file another one.
