### ISSUE TITLE
How to show the dialog for more than one time?

### ISSUE THREAD

**Issue by imprakharshukla** [TonnyL/WhatsNew#14]
I was implementing this library and first of all thank you for making my work a bit less with **WhatsNew** 
I am creating the instance for creating the dialog when a user clicks a card and with what I've encountered till now it seems like I am only able to create the dialog once, calling it the second time does nothing. Any solutions for this, I want the change to persist the whole time.

**Comment by TonnyL** [comment]
Hi, @imprakharshukla 

emmmm, it's a missing feature and I'll add it at next release.
