### ISSUE TITLE
ClassCastException on Create

### ISSUE THREAD

**Issue by csaq7151** [TonnyL/WhatsNew#5]
Recently I get this crash very often. Is there a way to fix it ?
Crashes occured on Android 9 and Android 6 on different phones. 

```
Caused by java.lang.ClassCastException
android.os.Parcelable[] cannot be cast to io.github.tonnyl.whatsnew.item.WhatsNewItem[]
at io.github.tonnyl.whatsnew.WhatsNew.onCreate (WhatsNew.kt:63)
com.mypackage.MainActivity.onCreate (MainActivity.java:30)
```

I have only drawables and text in the WhatsNewItems like in the example.

**Comment by TonnyL** [comment]
OK, will check it later 😀

**Comment by TonnyL** [comment]
Hi @csaq7151 

v0.1.2 released 🎉, try this version and check if it solve that crash.

**Comment by csaq7151** [comment]
Hi @TonnyL 
I included it in my app. So far no new crashes.
Thank you !

**Comment by TonnyL** [comment]
Glad to hear that 😉
